describe('Sad path testing', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
    
  })

  it('Should be able to see proper message if no data is retrieved when searching for cities', () => {
    cy.intercept('Get', 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities?limit=20&countryIds=Q30&minPopulation=600000', {})
    .as('big-cities-search-error')
    .get(':nth-child(3) > .css-1yrzk2j > .MuiTypography-root')
    .click()
    .get('h3')
    .should('contain', 'Something went wrong, please try again later')
  })

  it('Should be able to see a message if no image and information of the city was retrieved', () => {
    cy.visit('http://localhost:3000/Chicago/IL/41.8819/-87.6278')
    .intercept('https://en.wikipedia.org/api/rest_v1/page/summary/Chicago', { })
    .as('chicago-wiki-error')
    .intercept('https://fe-cors-proxy.herokuapp.com/', {})
    .as('chicago-walk-score-error')
    .get('h2')
    .should('contain', 'We are sorry, we don\'t have an image for this city')
    .get('h3')
    .should('contain', 'We are sorry, try again with another city')
  })

  it('Should be able to see a message if comparison chart is full', () => {
    cy.intercept('Get', 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities?limit=20&countryIds=Q30&minPopulation=600000', { fixture: 'bigCities'})
    .as('big-cities-stub')
    .intercept('https://en.wikipedia.org/api/rest_v1/page/summary/Memphis', { fixture: 'memphisWiki'})
    .as('memphis wiki')
    .intercept('https://fe-cors-proxy.herokuapp.com/', { fixture: 'memphisWalkScores'})
    .as('memphis walkscore')
    .get(':nth-child(3) > .css-1yrzk2j > .MuiTypography-root')
    .click()
    .get(':nth-child(1) > .MuiCardActions-root > .MuiButton-root')
    .click()
    .get('.MuiButton-contained')
    .click()
    .get('.MuiCardActions-root > .MuiButton-text')
    .click()
    .intercept('Get', 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities?limit=20&countryIds=Q30&minPopulation=600000', { fixture: 'bigCities'})
    .as('big-cities-stub')
    .intercept('https://en.wikipedia.org/api/rest_v1/page/summary/Chicago', { fixture: 'chicagoWiki'})
    .as('chicago wiki')
    .intercept('https://fe-cors-proxy.herokuapp.com/', { fixture: 'chicagoWalkScores'})
    .as('chicago walkScores')
    .get(':nth-child(2) > .MuiCardActions-root > .MuiButton-root')
    .click()
    .get('.MuiButton-contained')
    .click()
    .get('.MuiCardActions-root > .MuiButton-text')
    .click()
    .intercept('Get', 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities?limit=20&countryIds=Q30&minPopulation=600000', { fixture: 'bigCities'})
    .as('big-cities-stub')
    .intercept('https://en.wikipedia.org/api/rest_v1/page/summary/Denver', { fixture: 'denverWiki'})
    .as('denver wiki')
    .intercept('https://fe-cors-proxy.herokuapp.com/', { fixture: 'denverWalkScores'})
    .as('denver walkScores')
    .get(':nth-child(3) > .MuiCardActions-root > .MuiButton-root')
    .click()
    .get('.MuiButton-contained')
    .click()
    .get('.overview-nav > :nth-child(3)')
    .click()
    .get(':nth-child(2) > .MuiCardActions-root > .MuiTypography-root')
    .should('contain', 'You\'re ready to compare')
    .get(':nth-child(2) > .MuiCardActions-root > .MuiButton-contained')
    .should('contain', 'Delete')
  })

  it('Should be able to se a proper message if comparison chart is empty', () => {
    cy.intercept('Get', 'https://wft-geo-db.p.rapidapi.com/v1/geo/cities?limit=20&countryIds=Q30&minPopulation=600000', { fixture: 'bigCities'})
    .as('big-cities-stub')
    .get(':nth-child(3) > .css-1yrzk2j > .MuiTypography-root')
    .click()
    .get('.nav > :nth-child(3)')
    .click()
    .get('h2')
    .should('contain', 'Try adding some cities to compare')
  })
})